# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  exec_config = debug

else ifeq ($(config),release)
  exec_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := exec

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

exec:
ifneq (,$(exec_config))
	@echo "==== Building exec ($(exec_config)) ===="
	@${MAKE} --no-print-directory -C . -f exec.make config=$(exec_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f exec.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   exec"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"